version: 2.1

jobs:
  build-and-push-image:
    docker:
      - image: landedhomes/buildpack-deps
        auth:
          username: landedhomes
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/postgres/
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build Docker image
          command: cd development && docker build -t landedhomes/postgres:development .
      - run:
          name: Push Docker image
          command: docker push landedhomes/postgres:development

workflows:
  version: 2
  workflow:
    jobs:
      - build-and-push-image:
          #filters:
            #branches:
              #only:
                #- main
          context:
            - docker-hub-creds
